ARG ARCH=amd64
FROM registry.erda.cloud/k4s/$ARCH/golang:1.17-buster AS builder

WORKDIR /workspace

COPY api/ api/
COPY controllers/ controllers/
COPY pkg/ pkg/
COPY cmd/ cmd/
COPY go.mod go.mod
COPY go.sum go.sum
RUN GOPROXY=https://goproxy.cn,direct CGO_ENABLED=0 GOOS=linux go build -a -o mylet ./cmd/mylet/

FROM registry.erda.cloud/k4s/$ARCH/mysql:8.0.38

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
  echo Asia/Shanghai > /etc/timezone

RUN set -eux; \
    echo "deb http://mirrors.aliyun.com/debian bookworm main contrib non-free non-free-firmware" > /etc/apt/sources.list; \
    echo "deb http://mirrors.aliyun.com/debian bookworm-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list; \
    echo "deb http://mirrors.aliyun.com/debian-security bookworm-security main contrib non-free non-free-firmware" >> /etc/apt/sources.list; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        curl \
        procps \
        iproute2 \
        net-tools \
        less \
        lsof \
        bash; \
    curl -fSL -o /tmp/xtrabackup.deb "http://erda-project.oss-cn-hangzhou.aliyuncs.com/erda-addons/percona-xtrabackup-80_8.0.35-34-1.bookworm_$(uname -m).deb"; \
    apt-get install -y /tmp/xtrabackup.deb; \
    rm -f /tmp/xtrabackup.deb; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*

WORKDIR /
COPY --from=builder /workspace/mylet .
VOLUME /mydir
EXPOSE 3306 33080
USER mysql:mysql
ENTRYPOINT []
CMD ["/mylet"]
