apiVersion: v1
kind: Service
metadata:
  labels:
    addon: myctl
  name: myctl-metrics-service
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    addon: myctl
